### ISSUE TITLE
Generic Dispatch Proposal

### ISSUE THREAD

**Issue by ghost** [zibings/stoic-php-chain#5]
This proposal is to create a generic dispatch that could store dynamic data in an array. The dispatch could then pass that dynamic data along the chain. This generic dispatch would basically serve as an out of the box solution for developers to get started with.

The dispatch would need to have methods to set, retrieve and clear the dynamic values, along with the option of retrieving the sanitized values. Below is a suggestion for the interface.

`$dispatch->set($name, $value);`
`$dispatch->get($name, $default);`
`$dispatch->getAll();`
`$dispatch->getArray($name, $default = array());`
`$dispatch->getBool($name, $default = true);`
`$dispatch->getFloat($name, $default = 0.0);`
`$dispatch->getInteger($name, $default = 0);`
`$dispatch->getString($name, $default = '');`
`$dispatch->clear();`

Thank you for reading this proposal. Please leave any comments or suggestions below.

**Comment by AndyM84** [comment]
So wouldn't this be shared functionality between the `ParameterHelper` (elsewhere) and this generic dispatch?  Should we really do that, or should you just get maybe a `ParameterDispatch` wherever the `ParameterHelper` is that provides the functionality?  Otherwise I like the idea of having one or more basic dispatches as a sort of 'starter kit'.

**Comment by AndyM84** [comment]
Closing per discussion with @c-butcher about putting some generic/starter dispatches in other components, like web.
